size_t mc_util_strlen(const char *str);
char *mc_util_strdup(const char *string);
size_t mc_util_hashdata(const void *ptr, size_t len);
size_t mc_util_upperpowoftwo(size_t v);
PtrList *mc_util_splitstring(const char *str, const char *delimiter);
char *mc_util_joinstringarray(mcstate_t *state, PtrList *items, const char *joinee, size_t jlen);
mcvalue_t mc_value_copyflat(mcstate_t* state, mcvalue_t obj);
mcvalue_t mc_value_makearraycapacity(mcstate_t *state, size_t capacity);
mcvalue_t mc_value_makemapcapacity(mcstate_t *state, size_t capacity);
mcvalue_t mc_value_makeerrornocopy(mcstate_t *state, char *error);
bool mc_value_stringappendlen(mcvalue_t obj, const char *src, size_t len);
bool mc_value_stringrehash(mcvalue_t obj);
bool mc_value_arraypush(mcvalue_t object, mcvalue_t val);
bool mc_value_mapsetvalue(mcvalue_t object, mcvalue_t key, mcvalue_t val);
bool mc_value_callbackequals(mcvalue_t *aptr, mcvalue_t *bptr);
size_t mc_value_callbackhash(mcvalue_t *objptr);
void mc_printer_printvalue(Printer *pr, mcvalue_t obj, bool accurate);
void mc_errlist_clear(mcerrlist_t *errors);
mcerror_t *mc_errlist_get(mcerrlist_t *errors, int ix);
void mc_module_destroy(mcmodule_t *module);
void mc_astexpr_destroy(mcastexpression_t *expr);
mcastexpression_t *mc_astexpr_makedefineexpr(mcstate_t *state, mcastexprident_t *name, mcastexpression_t *value, bool assignable);
mcastexpression_t *mc_astexpr_makeifexpr(mcstate_t *state, PtrList *cases, mcastexprcodeblock_t *alternative);
mcastexpression_t *mc_astexpr_makereturnexpr(mcstate_t *state, mcastexpression_t *value);
mcastexpression_t *mc_astexpr_makeexprstmt(mcstate_t *state, mcastexpression_t *value);
mcastexpression_t *mc_astexpr_makewhileexpr(mcstate_t *state, mcastexpression_t *test, mcastexprcodeblock_t *body);
mcastexpression_t *mc_astexpr_makebreakexpr(mcstate_t *state);
mcastexpression_t *mc_astexpr_makeforeachexpr(mcstate_t *state, mcastexprident_t *iterator, mcastexpression_t *source, mcastexprcodeblock_t *body);
mcastexpression_t *mc_astexpr_makeforloopexpr(mcstate_t *state, mcastexpression_t *init, mcastexpression_t *test, mcastexpression_t *update, mcastexprcodeblock_t *body);
mcastexpression_t *mc_astexpr_makecontinueexpr(mcstate_t *state);
mcastexpression_t *mc_astexpr_makeblockexpr(mcstate_t *state, mcastexprcodeblock_t *block);
mcastexpression_t *mc_astexpr_makeimportexpr(mcstate_t *state, char *path);
mcastexpression_t *mc_astexpr_makerecoverexpr(mcstate_t *state, mcastexprident_t *eid, mcastexprcodeblock_t *body);
void mc_astcodeblock_destroy(mcastexprcodeblock_t *block);
mcastexprcodeblock_t *mc_astcodeblock_copy(mcastexprcodeblock_t *block);
mcastfuncparam_t *mc_astfuncparam_copy(mcastfuncparam_t *param);
void mc_astfuncparam_destroy(mcastfuncparam_t *param);
mcastexprident_t *mc_astident_make(mcstate_t *state, mcasttoken_t tok);
mcastexprident_t *mc_astident_copy(mcastexprident_t *ident);
void mc_astident_destroy(mcastexprident_t *ident);
void mc_astifcase_destroy(mcastexprifcase_t *cond);
mcastexprifcase_t *mc_astifcase_copy(mcastexprifcase_t *ifcase);
mcastexpression_t *mc_astexpr_makeexpression(mcstate_t *state, mcastexprtype_t type);
mcasttoken_t mc_lexer_nexttokinternal(mcastlexer_t *lex);
bool mc_lexer_readchar(mcastlexer_t *lex);
char mc_lexer_peekchar(mcastlexer_t *lex);
bool mc_lexer_charisletter(char ch);
bool mc_lexer_charisdigit(char ch);
const char *mc_lexer_scanident(mcastlexer_t *lex, int *outlen);
const char *mc_lexer_scannumber(mcastlexer_t *lex, int *outlen);
const char *mc_lexer_scanstring(mcastlexer_t *lex, char delimiter, bool istemplate, bool *outtemplatefound, int *outlen);
mcasttoktype_t mc_lexer_lookupident(const char *ident, int len);
void mc_lexer_skipspace(mcastlexer_t *lex);
bool mc_lexer_addline(mcastlexer_t *lex, int offset);
mcastexpression_t *mc_astparser_parsestatement(mcastparser_t *p);
mcastexpression_t *mc_parser_parsevarletstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseifstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parsereturnstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseexprstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseloopwhilestmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parsebreakstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parsecontinuestmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseblockstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseimportstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parserecoverstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseloopforloopstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseloopforeachstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parseloopforcstylestmt(mcastparser_t *p);
mcastexprcodeblock_t *mc_parser_parsecodeblock(mcastparser_t *p);
mcastexpression_t *mc_parser_parseexpression(mcastparser_t *p, mcastprecedence_t prec);
mcastexpression_t *mc_parser_parseident(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralnumber(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralbool(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralstring(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteraltemplatestring(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralnull(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralarray(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralmap(mcastparser_t *p);
mcastexpression_t *mc_parser_parseprefixexpr(mcastparser_t *p);
mcastexpression_t *mc_parser_parseinfixexpr(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_parser_parsegroupedexpr(mcastparser_t *p);
mcastexpression_t *mc_parser_parseliteralfunction(mcastparser_t *p);
mcastexpression_t *mc_parser_parsefunctionstmt(mcastparser_t *p);
mcastexpression_t *mc_parser_parsecallexpr(mcastparser_t *p, mcastexpression_t *left);
PtrList *mc_parser_parseexprlist(mcastparser_t *p, mcasttoktype_t starttoken, mcasttoktype_t endtoken, bool trailingcommaallowed);
mcastexpression_t *mc_parser_parseindexexpr(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_parser_parseassignexpr(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_parser_parselogicalexpr(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_parser_parseternaryexpr(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_parser_parseincdecprefixexpr(mcastparser_t *p);
mcastexpression_t *mc_parser_parseincdecpostfixexpr(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_parser_parsedotexpression(mcastparser_t *p, mcastexpression_t *left);
mcastexpression_t *mc_optimizer_optinfixexpr(mcastexpression_t *expr);
mcastexpression_t *mc_optimizer_optprefixexpr(mcastexpression_t *expr);
void mc_astcompscope_destroy(mcastscopecomp_t *scope);
mccompiledprogram_t *mc_astcompresult_make(mcstate_t *state, uint16_t *bytecode, mcastlocation_t *srcposlist, int count);
void mc_astcompresult_destroy(mccompiledprogram_t *res);
void mc_compiler_deinit(mcastcompiler_t *comp);
mcopdefinition_t *mc_opdef_lookup(mcopdefinition_t *def, mcinternopcode_t op);
mcastscopecomp_t *mc_compiler_getcompilationscope(mcastcompiler_t *comp);
bool mc_compiler_pushcompilationscope(mcastcompiler_t *comp);
void mc_compiler_popcompilationscope(mcastcompiler_t *comp);
bool mc_compiler_compilestmtlist(mcastcompiler_t *comp, PtrList *statements);
bool mc_compiler_compileexpression(mcastcompiler_t *comp, mcastexpression_t *expr);
bool mc_compiler_compilecodeblock(mcastcompiler_t *comp, mcastexprcodeblock_t *block);
int mc_compiler_addconstant(mcastcompiler_t *comp, mcvalue_t obj);
void mc_compiler_changeuint16operand(mcastcompiler_t *comp, int ip, uint16_t operand);
bool mc_compiler_lastopcodeis(mcastcompiler_t *comp, mcinternopcode_t op);
bool mc_compiler_readsymbol(mcastcompiler_t *comp, mcastsymbol_t *symbol);
bool mc_compiler_storesymbol(mcastcompiler_t *comp, mcastsymbol_t *symbol, bool define);
bool mc_compiler_pushbreakip(mcastcompiler_t *comp, int ip);
void mc_compiler_popbreakip(mcastcompiler_t *comp);
int mc_compiler_getbreakip(mcastcompiler_t *comp);
bool mc_compiler_pushcontinueip(mcastcompiler_t *comp, int ip);
void mc_compiler_popcontinueip(mcastcompiler_t *comp);
int mc_compiler_getcontinueip(mcastcompiler_t *comp);
int mc_compiler_getip(mcastcompiler_t *comp);
PtrList *mc_compiler_getsrcpositions(mcastcompiler_t *comp);
PtrList *mc_compiler_getbytecode(mcastcompiler_t *comp);
void mc_compiler_filescopedestroy(mcastscopefile_t *scope);
bool mc_compiler_filescopepush(mcastcompiler_t *comp, const char *filepath);
void mc_compiler_filescopepop(mcastcompiler_t *comp);
void mc_compiler_setcompilationscope(mcastcompiler_t *comp, mcastscopecomp_t *scope);
mcastcompiledfile_t *mc_compiledfile_make(mcstate_t *state, const char *path);
void mc_compiledfile_destroy(mcastcompiledfile_t *file);
mcastsymtable_t *mc_compiler_getsymtable(mcastcompiler_t *comp);
void mc_compiler_setsymtable(mcastcompiler_t *comp, mcastsymtable_t *table);
void mc_state_deinit(mcstate_t *state);
void mc_state_setdefaultconfig(mcstate_t *state);
int mc_state_errorcount(mcstate_t *state);
void mc_state_clearerrors(mcstate_t *state);
mcerror_t *mc_state_geterror(mcstate_t *state, int index);
bool mc_state_setglobalconstant(mcstate_t *state, const char *name, mcvalue_t obj);
mcvalue_t mc_state_getglobalobjectbyname(mcstate_t *state, const char *name);
const char *mc_util_errortypename(mcerrtype_t type);
bool mc_error_printusererror(Printer *pr, mcvalue_t obj);
mctraceback_t *mc_error_gettraceback(mcerror_t *error);
void mc_astprinter_printast(mcstate_t *state, PtrList *statements);
void mc_astprint_stmtlist(mcastprinter_t *apr, PtrList *statements);
void mc_astprint_expression(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_codeblock(mcastprinter_t *apr, mcastexprcodeblock_t *blockexpr);
const char *mc_util_mathopstring(mcastmathoptype_t op);
mcgcmemory_t *mc_gcmemory_make(mcstate_t *state);
void mc_gcmemory_destroy(mcgcmemory_t *mem);
mcobjdata_t *mc_gcmemory_allocobjectdata(mcstate_t *state);
mcobjdata_t *mc_gcmemory_getdatafrompool(mcstate_t *state, mcvaltype_t type);
void mc_state_gcmarkobject(mcvalue_t obj);
mcgcobjdatapool_t *mc_state_gcgetpoolfortype(mcstate_t *state, mcvaltype_t type);
bool mc_state_gccandatabeputinpool(mcstate_t *state, mcobjdata_t *data);
mcglobalstore_t *mc_globalstore_make(mcstate_t *state);
void mc_globalstore_destroy(mcglobalstore_t *store);
bool mc_globalstore_setnamed(mcglobalstore_t *store, const char *name, mcvalue_t object);
mcvalue_t mc_globalstore_getatindex(mcglobalstore_t *store, int ix, bool *outok);
mcastsymbol_t *mc_symbol_make(mcstate_t *state, const char *name, mcastsymtype_t type, int index, bool assignable);
void mc_symbol_destroy(mcastsymbol_t *symbol);
mcastsymbol_t *mc_symbol_copy(mcastsymbol_t *symbol);
mcastsymtable_t *mc_symtable_make(mcstate_t *state, mcastsymtable_t *outer, mcglobalstore_t *gstore, int mgo);
void mc_symtable_destroy(mcastsymtable_t *table);
mcastsymtable_t *mc_symtable_copy(mcastsymtable_t *table);
bool mc_symtable_addmodsymbol(mcastsymtable_t *st, mcastsymbol_t *symbol);
mcastsymbol_t *mc_symtable_define(mcastsymtable_t *table, const char *name, bool assignable);
mcastsymbol_t *mc_symtable_definefunctionname(mcastsymtable_t *st, const char *name, bool assignable);
mcastsymbol_t *mc_symtable_definethis(mcastsymtable_t *st);
mcastsymbol_t *mc_symtable_resolve(mcastsymtable_t *table, const char *name);
bool mc_symtable_isdefined(mcastsymtable_t *table, const char *name);
bool mc_symtable_pushblockscope(mcastsymtable_t *table);
void mc_symtable_popblockscope(mcastsymtable_t *table);
mcastscopeblock_t *mc_symtable_getblockscope(mcastsymtable_t *table);
bool mc_symtable_ismodglobalscope(mcastsymtable_t *table);
bool mc_symtable_istopglobalscope(mcastsymtable_t *table);
size_t mc_symtable_getmodglobalsymcount(mcastsymtable_t *table);
mcastsymbol_t *mc_symtable_getmodglobalsymat(mcastsymtable_t *table, int ix);
mcastscopeblock_t *mc_astblockscope_make(mcstate_t *state, int offset);
void mc_astblockscope_destroy(mcastscopeblock_t *scope);
mcastscopeblock_t *mc_astblockscope_copy(mcastscopeblock_t *scope);
bool mc_symtable_setsymbol(mcastsymtable_t *table, mcastsymbol_t *symbol);
int mc_symtable_nextsymindex(mcastsymtable_t *table);
int mc_symtable_getnumdefs(mcastsymtable_t *table);
void mc_asttoken_init(mcasttoken_t *tok, mcasttoktype_t type, const char *literal, int len);
char *mc_asttoken_dupliteralstring(mcasttoken_t *tok);
const char *mc_asttoken_typename(mcasttoktype_t type);
void mc_traceback_destroy(mctraceback_t *traceback);
const char *mc_traceitem_getsourceline(mctraceitem_t *item);
const char *mc_traceitem_getsourcefilepath(mctraceitem_t *item);
bool mc_vm_init(mcstate_t *state);
void mc_vm_reset(mcstate_t *state);
mcvalue_t mc_vm_getglobalbyindex(mcstate_t *state, size_t ix);
void mc_vm_stackpush(mcstate_t *state, mcvalue_t obj);
bool mc_vm_popframe(mcstate_t *state);
void mc_state_makestdclasses(mcstate_t *state);
void dyn_strbuf_touppercase(StringBuffer *sbuf);
void dyn_strbuf_tolowercase(StringBuffer *sbuf);
