
void optprs_fprintmaybearg(FILE *out, const char *begin, const char *flagname, size_t flaglen, bool needval, bool maybeval, const char *delim);
void optprs_fprintusage(FILE *out, optlongflags_t *flags);
void optprs_printusage(char *argv[], optlongflags_t *flags, bool fail);
uint64_t stod_leading_zeros64(uint64_t x);
double stod_diyfp2d(mcstoddiyfp_t v);
mcstoddiyfp_t stod_diyfp_shift_left(mcstoddiyfp_t v, unsigned shift);
mcstoddiyfp_t stod_diyfp_shift_right(mcstoddiyfp_t v, unsigned shift);
mcstoddiyfp_t stod_diyfp_mul(mcstoddiyfp_t lhs, mcstoddiyfp_t rhs);
mcstoddiyfp_t stod_diyfp_normalize(mcstoddiyfp_t v);
uint64_t stod_read_uint64(const unsigned char *start, size_t length, size_t *ndigits);
mcstoddiyfp_t stod_cached_power_dec(int exp, int *dec_exp);
mcstoddiyfp_t stod_adjust_pow10(int exp);
int stod_diyfp_sgnd_size(int order);
double stod_strtod(const unsigned char **start, const unsigned char *end, int literal);
char *mc_util_readhandle(FILE *hnd, size_t *dlen);
char *mc_util_readfile(const char *filename, size_t *dlen);
char *mc_fsutil_fileread(const char *filename, size_t *flen);
size_t mc_fsutil_filewrite(const char *path, const char *string, size_t stringsize);
size_t mc_util_strlen(const char *str);
char *mc_util_strndup(const char *string, size_t n);
char *mc_util_strdup(const char *string);
bool mc_util_strequal(const char *a, const char *b);
bool mc_util_strnequal(const char *a, const char *b, size_t len);
char *mc_util_canonpath(const char *path);
bool mc_util_pathisabsolute(const char *path);
size_t mc_util_hashdata(const void *ptr, size_t len);
size_t mc_util_hashdouble(mcfloat_t val);
size_t mc_util_upperpowoftwo(size_t v);
mcfloat_t mc_util_strtod(const char *str, size_t slen, char **endptr);
PtrList *mc_util_splitstring(const char *str, const char *delimiter);
char *mc_util_joinstringarray(PtrList *items, const char *joinee, size_t jlen);
uint64_t mc_util_doubletouint64(mcfloat_t val);
mcfloat_t mc_util_uint64todouble(uint64_t val);
const char *mc_valtype_getname(mcvaltype_t type);
const char *mc_value_objtypename(mcvaltype_t type);


mcvalue_t mc_value_makestrcapacity(mcstate_t *state, int capacity);
mcvalue_t mc_value_makestringlen(mcstate_t *state, const char *string, size_t len);
mcvalue_t mc_value_makestring(mcstate_t *state, const char *string);
mcvalue_t mc_value_makefuncnative(mcstate_t *state, const char *name, mcnativefn_t fn, void *data);
mcvalue_t mc_value_makearray(mcstate_t *state);
mcvalue_t mc_value_makearraycapacity(mcstate_t *state, size_t capacity);
mcvalue_t mc_value_makemap(mcstate_t *state);
mcvalue_t mc_value_makemapcapacity(mcstate_t *state, size_t capacity);
mcvalue_t mc_value_makeerror(mcstate_t *state, const char *error);
mcvalue_t mc_value_makeerrornocopy(mcstate_t *state, char *error);
mcvalue_t mc_value_makefuncscript(mcstate_t *state, const char *name, mccompiledprogram_t *cres, bool ownsdt, int nlocals, int nargs, int fvc);
mcvalue_t mc_value_makeuserobject(mcstate_t *state, void *data);
mcobjuserdata_t *mc_value_userdatagetdata(mcvalue_t object);
bool mc_value_userdatasetdata(mcvalue_t object, void *extdata);
bool mc_value_userdatasetdestroyfunction(mcvalue_t object, mcitemdestroyfn_t dfn);
bool mc_value_userdatasetcopyfunction(mcvalue_t object, mcitemcopyfn_t copyfn);
bool mc_value_asbool(mcvalue_t obj);
mcfloat_t mc_value_asnumber(mcvalue_t obj);
int mc_value_stringgetlength(mcvalue_t object);
void mc_value_stringsetlength(mcvalue_t object, int len);
bool mc_value_stringappendlen(mcvalue_t obj, const char *src, size_t len);
bool mc_value_stringappend(mcvalue_t obj, const char *src);
bool mc_value_stringappendvalue(mcvalue_t destval, mcvalue_t val);
size_t mc_value_stringgethash(mcvalue_t obj);
bool mc_value_stringrehash(mcvalue_t obj);
mcobjfunction_t *mc_value_asscriptfunction(mcvalue_t object);
const char *mc_value_functiongetname(mcvalue_t obj);
mcvalue_t mc_value_functiongetfreevalat(mcvalue_t obj, int ix);
void mc_value_functionsetfreevalat(mcvalue_t obj, int ix, mcvalue_t val);
mcvalue_t *mc_value_functiongetfreevals(mcvalue_t obj);
const char *mc_value_errorgetmessage(mcvalue_t object);
void mc_value_errorsettraceback(mcvalue_t object, mctraceback_t *traceback);
mctraceback_t *mc_value_errorgettraceback(mcvalue_t object);
mcvalue_t mc_value_arraygetvalue(mcvalue_t object, size_t ix);
bool mc_value_arraysetvalue(mcvalue_t object, size_t ix, mcvalue_t val);
bool mc_value_arraypush(mcvalue_t object, mcvalue_t val);
int mc_value_arraygetlength(mcvalue_t object);
mcvalue_t mc_valarray_pop(mcvalue_t object);
bool mc_value_arrayremoveat(mcvalue_t object, int ix);
int mc_value_mapgetlength(mcvalue_t object);
mcvalue_t mc_value_mapgetkeyat(mcvalue_t object, int ix);
mcvalue_t mc_value_mapgetvalueat(mcvalue_t object, int ix);
bool mc_value_mapsetvalueat(mcvalue_t object, int ix, mcvalue_t val);
mcvalue_t mc_value_mapgetkvpairat(mcstate_t *state, mcvalue_t object, int ix);
bool mc_value_mapsetvalue(mcvalue_t object, mcvalue_t key, mcvalue_t val);
bool mc_value_mapsetvaluestring(mcvalue_t object, const char *strkey, mcvalue_t val);
mcvalue_t mc_value_mapgetvalue(mcvalue_t object, mcvalue_t key);
bool mc_value_mapgetvaluechecked(mcvalue_t object, mcvalue_t key, mcvalue_t *dest);
bool mc_value_maphaskey(mcvalue_t object, mcvalue_t key);
void mc_objectdata_deinit(mcobjdata_t *data);
bool mc_value_callbackequals(mcvalue_t *aptr, mcvalue_t *bptr);
size_t mc_value_callbackhash(mcvalue_t *objptr);
mcvalue_t mc_value_copydeep(mcstate_t *state, mcvalue_t obj);
mcvalue_t mc_value_copyflat(mcstate_t *state, mcvalue_t obj);

bool mc_printutil_bcreadoperands(mcopdefinition_t *def, const uint16_t *instr, uint64_t outoperands[2]);
void mc_printer_printoneinstruc(Printer *pr, uint16_t *code, uint16_t op, size_t *pos, mcastlocation_t *sposlist, bool simple);
void mc_printer_printbytecode(Printer *pr, uint16_t *code, mcastlocation_t *sposlist, size_t codesize, bool simple);
void mc_printer_printobjstring(Printer *pr, mcvalue_t obj);
void mc_printer_printobjfuncscript(Printer *pr, mcvalue_t obj);
void mc_printer_printobjarray(Printer *pr, mcvalue_t obj);
void mc_printer_printobjmap(Printer *pr, mcvalue_t obj);
void mc_printer_printobjerror(Printer *pr, mcvalue_t obj);
void mc_consolecolor_init(mcconsolecolor_t *mcc, int fd);
const char *mc_consolecolor_get(mcconsolecolor_t *mcc, char code);
void mc_printer_printvalue(Printer *pr, mcvalue_t obj, bool accurate);
mcastlocation_t mc_astlocation_make(mcastcompiledfile_t *file, int line, int column);
GCMemory *mc_value_getmem(mcvalue_t obj);
char *mc_valtype_getunionname(mcvaltype_t type);


mcastexpression_t *mc_astexpr_makedefineexpr(mcstate_t *state, mcastexprident_t *name, mcastexpression_t *value, bool assignable);;
mcastexpression_t *mc_astexpr_makeifexpr(mcstate_t *state, PtrList *cases, mcastexprcodeblock_t *alternative);;
mcastexpression_t *mc_astexpr_makereturnexpr(mcstate_t *state, mcastexpression_t *value);;
mcastexpression_t *mc_astexpr_makeexprstmt(mcstate_t *state, mcastexpression_t *value);;
mcastexpression_t *mc_astexpr_makewhileexpr(mcstate_t *state, mcastexpression_t *test, mcastexprcodeblock_t *body);;
mcastexpression_t *mc_astexpr_makebreakexpr(mcstate_t *state);;
mcastexpression_t *mc_astexpr_makeforeachexpr(mcstate_t *state, mcastexprident_t *iterator, mcastexpression_t *source, mcastexprcodeblock_t *body);;
mcastexpression_t *mc_astexpr_makeforloopexpr(mcstate_t *state, mcastexpression_t *init, mcastexpression_t *test, mcastexpression_t *update, mcastexprcodeblock_t *body);;
mcastexpression_t *mc_astexpr_makecontinueexpr(mcstate_t *state);;
mcastexpression_t *mc_astexpr_makeblockexpr(mcstate_t *state, mcastexprcodeblock_t *block);;
mcastexpression_t *mc_astexpr_makeimportexpr(mcstate_t *state, char *path);;
mcastexpression_t *mc_astexpr_makerecoverexpr(mcastexprident_t *eid, mcastexprcodeblock_t *body);;
mcastexpression_t* mc_astexpr_makeident(mcstate_t* state, mcastexprident_t* ident);
mcastexpression_t* mc_astexpr_makeliteralnumber(mcstate_t* state, mcfloat_t val);
mcastexpression_t* mc_astexpr_makeliteralbool(mcstate_t* state, bool val);
mcastexpression_t* mc_astexpr_makeliteralstring(mcstate_t* state, char* value, size_t len);
mcastexpression_t* mc_astexpr_makeliteralnull(mcstate_t* state);
mcastexpression_t* mc_astexpr_makeliteralarray(mcstate_t* state, PtrList* values);
mcastexpression_t* mc_astexpr_makeliteralmap(mcstate_t* state, PtrList* keys, PtrList* values);
mcastexpression_t* mc_astexpr_makeprefixexpr(mcstate_t* state, mcastmathoptype_t op, mcastexpression_t* right);
mcastexpression_t* mc_astexpr_makeinfixexpr(mcstate_t* state, mcastmathoptype_t op, mcastexpression_t* left, mcastexpression_t* right);
mcastexpression_t* mc_astexpr_makeliteralfunction(mcstate_t* state, PtrList* params, mcastexprcodeblock_t* body);
mcastexpression_t* mc_astexpr_makecallexpr(mcstate_t* state, mcastexpression_t* function, PtrList* args);
mcastexpression_t* mc_astexpr_makeindexexpr(mcstate_t* state, mcastexpression_t* left, mcastexpression_t* index, bool isdot);
mcastexpression_t* mc_astexpr_makeassignexpr(mcstate_t* state, mcastexpression_t* dest, mcastexpression_t* source, bool is_postfix);
mcastexpression_t* mc_astexpr_makelogicalexpr(mcstate_t* state, mcastmathoptype_t op, mcastexpression_t* left, mcastexpression_t* right);
mcastexpression_t* mc_astexpr_maketernaryexpr(mcstate_t* state, mcastexpression_t* test, mcastexpression_t* ift, mcastexpression_t* iffalse);
mcastexpression_t* mc_parser_makefunccallexpr(mcstate_t* state, mcastexpression_t* expr, const char* fname);
mcastexprifcase_t* mc_astifcase_make(mcastexpression_t* test, mcastexprcodeblock_t* consequence);
mcastfuncparam_t* mc_astfuncparam_make(mcastexprident_t* ident);
mcastexprcodeblock_t* mc_astcodeblock_make(PtrList* statements);
mcastexpression_t* mc_astexpr_makedefineexpr(mcstate_t* state, mcastexprident_t* name, mcastexpression_t* value, bool assignable);
mcastexpression_t* mc_astexpr_makeifexpr(mcstate_t* state, PtrList* cases, mcastexprcodeblock_t* alternative);
mcastexpression_t* mc_astexpr_makereturnexpr(mcstate_t* state, mcastexpression_t* value);
mcastexpression_t* mc_astexpr_makeexprstmt(mcstate_t* state, mcastexpression_t* value);
mcastexpression_t* mc_astexpr_makewhileexpr(mcstate_t* state, mcastexpression_t* test, mcastexprcodeblock_t* body);
mcastexpression_t* mc_astexpr_makebreakexpr(mcstate_t* state);
mcastexpression_t* mc_astexpr_makeforeachexpr(mcstate_t* state, mcastexprident_t* iterator, mcastexpression_t* source, mcastexprcodeblock_t* body);
mcastexpression_t* mc_astexpr_makeforloopexpr(mcstate_t* state, mcastexpression_t* init, mcastexpression_t* test, mcastexpression_t* update, mcastexprcodeblock_t* body);
mcastexpression_t* mc_astexpr_makecontinueexpr(mcstate_t* state);
mcastexpression_t* mc_astexpr_makeblockexpr(mcstate_t* state, mcastexprcodeblock_t* block);
mcastexpression_t* mc_astexpr_makeimportexpr(mcstate_t* state, char* path);
mcastexpression_t* mc_astexpr_makerecoverexpr(mcstate_t* state, mcastexprident_t* eid, mcastexprcodeblock_t* body);
void mc_astcodeblock_destroy(mcastexprcodeblock_t *block);
mcastexprcodeblock_t *mc_astcodeblock_copy(mcastexprcodeblock_t *block);
mcastfuncparam_t *mc_astfuncparam_copy(mcastfuncparam_t *param);
void mc_astfuncparam_destroy(mcastfuncparam_t *param);
mcastexprident_t *mc_astident_make(mcasttoken_t tok);
mcastexprident_t *mc_astident_copy(mcastexprident_t *ident);
void mc_astident_destroy(mcastexprident_t *ident);
void mc_astifcase_destroy(mcastexprifcase_t *cond);
mcastexprifcase_t *mc_astifcase_copy(mcastexprifcase_t *ifcase);


mcastexpression_t *mc_optimizer_optinfixexpr(mcastexpression_t *expr);
mcastexpression_t *mc_optimizer_optprefixexpr(mcastexpression_t *expr);
void mc_astcompscope_destroy(mcastscopecomp_t *scope);
mccompiledprogram_t *mc_astcompresult_make(mcstate_t *state, uint16_t *bytecode, mcastlocation_t *srcposlist, int count);
void mc_astcompresult_destroy(mccompiledprogram_t *res);
void mc_compiler_deinit(mcastcompiler_t *comp);
mcopdefinition_t *mc_opdef_lookup(mcopdefinition_t *def, mcinternopcode_t op);
mcastscopecomp_t *mc_compiler_getcompilationscope(mcastcompiler_t *comp);
bool mc_compiler_pushcompilationscope(mcastcompiler_t *comp);
void mc_compiler_popcompilationscope(mcastcompiler_t *comp);
bool mc_compiler_compilestmtlist(mcastcompiler_t *comp, PtrList *statements);
bool mc_compiler_compileexpression(mcastcompiler_t *comp, mcastexpression_t *expr);
bool mc_compiler_compilecodeblock(mcastcompiler_t *comp, mcastexprcodeblock_t *block);
int mc_compiler_addconstant(mcastcompiler_t *comp, mcvalue_t obj);
void mc_compiler_changeuint16operand(mcastcompiler_t *comp, int ip, uint16_t operand);
bool mc_compiler_lastopcodeis(mcastcompiler_t *comp, mcinternopcode_t op);
bool mc_compiler_readsymbol(mcastcompiler_t *comp, mcastsymbol_t *symbol);
bool mc_compiler_storesymbol(mcastcompiler_t *comp, mcastsymbol_t *symbol, bool define);
bool mc_compiler_pushbreakip(mcastcompiler_t *comp, int ip);
void mc_compiler_popbreakip(mcastcompiler_t *comp);
int mc_compiler_getbreakip(mcastcompiler_t *comp);
bool mc_compiler_pushcontinueip(mcastcompiler_t *comp, int ip);
void mc_compiler_popcontinueip(mcastcompiler_t *comp);
int mc_compiler_getcontinueip(mcastcompiler_t *comp);
int mc_compiler_getip(mcastcompiler_t *comp);

PtrList *mc_compiler_getsrcpositions(mcastcompiler_t *comp);
PtrList *mc_compiler_getbytecode(mcastcompiler_t *comp);
mcastscopefile_t *mc_compiler_filescopemake(mcastcompiler_t *comp, mcastcompiledfile_t *file);
void mc_compiler_filescopedestroy(mcastscopefile_t *scope);
bool mc_compiler_filescopepush(mcastcompiler_t *comp, const char *filepath);
void mc_compiler_filescopepop(mcastcompiler_t *comp);
void mc_compiler_setcompilationscope(mcastcompiler_t *comp, mcastscopecomp_t *scope);
mcastcompiledfile_t *mc_compiledfile_make(mcstate_t *state, const char *path);
void mc_compiledfile_destroy(mcastcompiledfile_t *file);
mcastcompiler_t *mc_compiler_make(mcstate_t *state, mcconfig_t *config, GCMemory *gcmem, mcerrlist_t *errors, PtrList *files, mcglobalstore_t *gstore);
void mc_compiler_destroy(mcastcompiler_t *comp);
mccompiledprogram_t *mc_compiler_compilesource(mcastcompiler_t *comp, const char *code, const char *filename);
mcastsymtable_t *mc_compiler_getsymtable(mcastcompiler_t *comp);
void mc_compiler_setsymtable(mcastcompiler_t *comp, mcastsymtable_t *table);

void mc_state_printerrors(mcstate_t *state);
mccompiledprogram_t *mc_state_compilesource(mcstate_t *state, const char *code, const char *filename);
mcvalue_t mc_program_execute(mcstate_t *state, mccompiledprogram_t *program);
void mc_program_destroy(mccompiledprogram_t *program);
mcvalue_t mc_state_execcode(mcstate_t *state, const char *code, const char *filename);
mcvalue_t mc_state_callfunctionbyname(mcstate_t *state, const char *fname, mcvalue_t thisval, size_t argc, mcvalue_t *args);
bool mc_state_haserrors(mcstate_t *state);
int mc_state_errorcount(mcstate_t *state);
void mc_state_clearerrors(mcstate_t *state);
mcerror_t *mc_state_geterror(mcstate_t *state, int index);
bool mc_state_setnativefunction(mcstate_t *state, const char *name, mcnativefn_t fn, void *data);
bool mc_state_setglobalconstant(mcstate_t *state, const char *name, mcvalue_t obj);
mcvalue_t mc_state_getglobalobjectbyname(mcstate_t *state, const char *name);
bool mc_error_printusererror(Printer *pr, mcvalue_t obj);


void mc_astprinter_printast(mcstate_t *state, PtrList *statements);
void mc_astprint_stmtlist(mcastprinter_t *apr, PtrList *statements);
void mc_astprint_printfuncliteral(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printcall(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printarrayliteral(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printstringliteral(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printmapliteral(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printprefixexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printinfixexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printindexexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printassignexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printlogicalexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printternaryexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printdefineexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printifexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printwhileexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printforclassicexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printforeachexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printimportexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_printrecoverexpr(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_expression(mcastprinter_t *apr, mcastexpression_t *astexpr);
void mc_astprint_codeblock(mcastprinter_t *apr, mcastexprcodeblock_t *blockexpr);
const char *mc_util_mathopstring(mcastmathoptype_t op);
bool mc_argcheck_check(mcstate_t *state, bool generateerror, size_t argc, mcvalue_t *args, ...);
bool mc_argcheck_checkactual(mcstate_t *state, bool generateerror, size_t argc, mcvalue_t *args, size_t expectedargc, const mcvaltype_t *expectedtypes);

mcobjdata_t *mc_gcmemory_allocobjectdata(mcstate_t *state);
mcobjdata_t *mc_gcmemory_getdatafrompool(mcstate_t *state, mcvaltype_t type);
void mc_state_gcunmarkall(mcstate_t *state);
void mc_state_gcmarkobjlist(mcvalue_t *objects, size_t count);
void mc_state_gcmarkobject(mcvalue_t obj);
void mc_state_gcsweep(mcstate_t *state);
int mc_state_gcshouldsweep(mcstate_t *state);
bool mc_state_gcdisablefor(mcvalue_t obj);
void mc_state_gcenablefor(mcvalue_t obj);

bool mc_state_gccandatabeputinpool(mcstate_t *state, mcobjdata_t *data);
mcglobalstore_t *mc_globalstore_make(mcstate_t *state);
void mc_globalstore_destroy(mcglobalstore_t *store);
mcastsymbol_t *mc_globalstore_getsymbol(mcglobalstore_t *store, const char *name);
bool mc_globalstore_setnamed(mcglobalstore_t *store, const char *name, mcvalue_t object);
mcvalue_t mc_globalstore_getatindex(mcglobalstore_t *store, int ix, bool *outok);
mcvalue_t *mc_globalstore_getdata(mcglobalstore_t *store);
int mc_globalstore_getcount(mcglobalstore_t *store);

mcastscopeblock_t *mc_astblockscope_make(int offset);
void mc_astblockscope_destroy(mcastscopeblock_t *scope);
mcastscopeblock_t *mc_astblockscope_copy(mcastscopeblock_t *scope);

void mc_asttoken_init(mcasttoken_t *tok, mcasttoktype_t type, const char *literal, int len);
char *mc_asttoken_dupliteralstring(mcasttoken_t *tok);
const char *mc_asttoken_typename(mcasttoktype_t type);
bool mc_traceback_vmpush(mctraceback_t *traceback, mcstate_t *state);
bool mc_vm_init(mcstate_t *state);
void mc_vm_reset(mcstate_t *state);
mcvalue_t mc_vm_getglobalbyindex(mcstate_t *state, size_t ix);
void mc_vm_stackpush(mcstate_t *state, mcvalue_t obj);
bool mc_vm_popframe(mcstate_t *state);
void mc_vmutil_getopinfo(mcopcode_t opc, const char **oname);
mcvalue_t mc_scriptfn_typeof(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_arrayfirst(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_arraylast(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_arrayrest(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_reverse(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_makearray(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_externalfn(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_vec2add(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_vec2sub(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_testcheckargs(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_maketestdict(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_squarearray(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_print(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_println(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_tostring(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnjson_stringify(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnnumber_chr(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_length(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_indexof(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_charcodefirst(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_charcodeat(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_charat(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_getself(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_tonumber(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_left(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_right(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_replaceall(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_replacefirst(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_trim(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_matchhelper(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args, bool icase);
mcvalue_t mc_objfnstring_matchglobcase(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_matchglobicase(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_tolower(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnstring_toupper(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnarray_length(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
void mc_vm_savestate(mcstate_t *state, mcexecstate_t *est);
void mc_vm_restorestate(mcstate_t *state, mcexecstate_t *est);
mcvalue_t mc_objfnarray_map(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnarray_push(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnarray_pop(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnarray_join(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnmap_length(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnutil_istype(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args, mcvaltype_t vt);
mcvalue_t mc_objfnobject_iscallable(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isstring(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isarray(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_ismap(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isnumber(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isbool(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isnull(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isfuncscript(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isexternal(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_iserror(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_objfnobject_isfuncnative(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
void mc_state_makestdclasses(mcstate_t *state);
mcvalue_t mc_scriptfn_isnan(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_range(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_keys(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_values(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_copy(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_copydeep(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_remove(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_removeat(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_error(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_crash(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_assert(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_randseed(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_random(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptutil_slicearray(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptutil_slicestring(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_scriptfn_slice(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_sqrt(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_pow(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_sin(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_cos(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_tan(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_log(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_ceil(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_floor(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnmath_abs(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnfile_writefile(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnfile_readfile(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnfile_join(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnfile_isdirectory(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnfile_isfile(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnfile_stat(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfndir_readdir(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
mcvalue_t mc_nsfnvm_hadrecovered(mcstate_t *state, void *data, mcvalue_t thisval, size_t argc, mcvalue_t *args);
void mc_cli_installbuiltins(mcstate_t *state);
void mc_cli_installjsondummy(mcstate_t *state);
void mc_cli_installjsconsole(mcstate_t *state);
void mc_cli_installmath(mcstate_t *state);
void mc_cli_installfauxjavascript(mcstate_t *state);
void mc_cli_installfileio(mcstate_t *state);
void mc_cli_installdir(mcstate_t *state);
void mc_cli_installvmvar(mcstate_t *state);
void mc_cli_installotherstuff(mcstate_t *state);
bool mc_cli_compileandrunsource(mcstate_t *state, mcvalue_t *vdest, const char *source, const char *filename);
bool mc_cli_compileandrunfile(mcstate_t *state, const char *filename);
void mc_cli_installargv(mcstate_t *state, int argc, char **argv, int beginat);
void mc_cli_printtypesize(const char *name, size_t sz);
void mc_cli_printtypesizes(void);
int main(int argc, char *argv[]);
/* mem.c */
void *mc_memory_malloc(size_t sz);
void *mc_memory_realloc(void *p, size_t nsz);
void *mc_memory_calloc(size_t count, size_t typsize);
void mc_memory_free(void *ptr);

/* utilos.c */
char *osfn_utilstrndup(const char *src, size_t len);
char *osfn_utilstrdup(const char *src);
bool fslib_diropen(FSDirReader *rd, const char *path);
bool fslib_dirread(FSDirReader *rd, FSDirItem *itm);
bool fslib_dirclose(FSDirReader *rd);
int osfn_fdopen(const char *path, int flags, int mode);
int osfn_fdcreat(const char *path, int mode);
int osfn_fdclose(int fd);
size_t osfn_fdread(int fd, void *buf, size_t count);
size_t osfn_fdwrite(int fd, const void *buf, size_t count);
size_t osfn_fdput(int fd, const void *buf, size_t count);
int osfn_chmod(const char *path, int mode);
char *osfn_realpath(const char *path, char *respath);
char *osfn_dirname(const char *path);
char *osfn_fallbackbasename(const char *opath);
char *osfn_basename(const char *path);
int osfn_isatty(int fd);
int osfn_symlink(const char *path1, const char *path2);
int osfn_symlinkat(const char *path1, int fd, const char *path2);
char *osfn_getcwd(char *buf, size_t size);
int osfn_lstat(const char *path, struct stat *buf);
int osfn_truncate(const char *path, size_t length);
unsigned int osfn_sleep(unsigned int seconds);
int osfn_gettimeofday(struct timeval *tp, void *tzp);
int osfn_mkdir(const char *path, size_t mode);
int osfn_chdir(const char *path);
bool osfn_fileexists(const char *filepath);
bool osfn_stat(const char *path, struct stat *st);
bool osfn_statisa(const char *path, struct stat *st, char kind);
bool osfn_pathcheck(const char *path, char mode);
bool osfn_pathisfile(const char *path);
bool osfn_pathisdirectory(const char *path);
/* fnmatch.h */
/* mem.h */
/* optparse.h */
void optprs_fprintusage(FILE *out, optlongflags_t *flags);
/* stod.h */
uint64_t stod_leading_zeros64(uint64_t x);
double stod_diyfp2d(mcstoddiyfp_t v);
mcstoddiyfp_t stod_diyfp_shift_left(mcstoddiyfp_t v, unsigned shift);
mcstoddiyfp_t stod_diyfp_shift_right(mcstoddiyfp_t v, unsigned shift);
mcstoddiyfp_t stod_diyfp_mul(mcstoddiyfp_t lhs, mcstoddiyfp_t rhs);
mcstoddiyfp_t stod_diyfp_normalize(mcstoddiyfp_t v);
uint64_t stod_read_uint64(const unsigned char *start, size_t length, size_t *ndigits);
mcstoddiyfp_t stod_cached_power_dec(int exp, int *dec_exp);
mcstoddiyfp_t stod_adjust_pow10(int exp);
int stod_diyfp_sgnd_size(int order);
double stod_strtod(const unsigned char **start, const unsigned char *end, int literal);
    