
TMPSTATIC void* mc_allocator_alloc(mcstate_t* state, size_t size);
TMPSTATIC void mc_allocator_free(mcstate_t* state, void* ptr);
char* mc_util_readhandle(FILE* hnd, size_t* dlen);
char* mc_util_readfile(const char* filename, size_t* dlen);
TMPSTATIC char* mc_fsutil_fileread(mcstate_t* state, const char* filename, size_t* flen);
TMPSTATIC size_t mc_fsutil_filewrite(mcstate_t* state, const char* path, const char* string, size_t stringsize);
TMPSTATIC bool mc_fsutil_fileexists(mcstate_t* state, const char* filename);
TMPSTATIC size_t mc_util_strlen(const char* str);
TMPSTATIC char* mc_util_strndup(mcstate_t* state, const char* string, size_t n);
TMPSTATIC char* mc_util_strdup(mcstate_t* state, const char* string);
TMPSTATIC unsigned long mc_util_hashdata(const void* ptr, size_t len);
TMPSTATIC unsigned long mc_util_hashdouble(mcfloat_t val);
TMPSTATIC unsigned int mc_util_upperpowoftwo(unsigned int v);
double mc_util_strtod(const char* str, size_t slen, char** endptr);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_binshiftleft(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_binshiftright(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_binor(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_binand(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_binxor(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_add(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_sub(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_mult(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_div(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC MCINLINE mcfloat_t mc_mathutil_mod(mcfloat_t dnleft, mcfloat_t dnright);
TMPSTATIC bool mc_genericdict_init(mcgenericdict_t* dict, mcstate_t* state, unsigned int initialcapacity, mcitemcopyfn_t copyfn, mcitemdestroyfn_t dfn);
TMPSTATIC void mc_genericdict_deinit(mcgenericdict_t* dict, bool freekeys);
TMPSTATIC mcgenericdict_t* mc_genericdict_make(mcstate_t* state, mcitemcopyfn_t copyfn, mcitemdestroyfn_t dfn);
TMPSTATIC void mc_genericdict_destroy(mcgenericdict_t* dict);
TMPSTATIC void mc_genericdict_destroyitemsanddict(mcgenericdict_t* dict);
TMPSTATIC unsigned int mc_genericdict_getcellindex(mcgenericdict_t* dict, const char* key, unsigned long hash, bool* outfound);
TMPSTATIC bool mc_genericdict_setinternal(mcgenericdict_t* dict, const char* ckey, char* mkey, void* value);
TMPSEMISTATIC bool mc_genericdict_growandrehash(mcgenericdict_t* dict);
TMPSTATIC void* mc_genericdict_getvalueat(mcgenericdict_t* dict, unsigned int ix);
TMPSTATIC const char* mc_genericdict_getkeyat(mcgenericdict_t* dict, unsigned int ix);
TMPSTATIC int mc_genericdict_count(mcgenericdict_t* dict);
TMPSTATIC bool mc_genericdict_set(mcgenericdict_t* dict, const char* key, void* value);
TMPSTATIC mcgenericdict_t* mc_genericdict_copy(mcgenericdict_t* dict);
TMPSTATIC void* mc_genericdict_get(mcgenericdict_t* dict, const char* key);
TMPUNUSED bool mc_genericdict_remove(mcgenericdict_t* dict, const char* key);
TMPSTATIC bool mc_valdict_init(mcvaldict_t* dict, mcstate_t* state, size_t ktsz, size_t vtsz, unsigned int initialcapacity);
TMPSTATIC void mc_valdict_deinit(mcvaldict_t* dict);
TMPSTATIC mcvaldict_t* mc_valdict_make(mcstate_t* state, size_t ktsz, size_t vtsz);
TMPSTATIC mcvaldict_t* mc_valdict_makecapacity(mcstate_t* state, unsigned int mincapacity, size_t ktsz, size_t vtsz);
TMPSTATIC void mc_valdict_destroy(mcvaldict_t* dict);
TMPSTATIC void mc_valdict_sethashfunction(mcvaldict_t* dict, mcitemhashfn_t hashfn);
TMPSTATIC void mc_valdict_setequalsfunction(mcvaldict_t* dict, mcitemcomparefn_t equalsfn);
TMPSTATIC bool mc_valdict_setkv(mcvaldict_t* dict, void* key, void* value);
TMPSTATIC void* mc_valdict_get(mcvaldict_t* dict, void* key);
TMPSTATIC void* mc_valdict_getkeyat(mcvaldict_t* dict, unsigned int ix);
TMPSTATIC void* mc_valdict_getvalueat(mcvaldict_t* dict, unsigned int ix);
TMPUNUSED unsigned int mc_valdict_getcapacity(mcvaldict_t* dict);
TMPSTATIC bool mc_valdict_setvalueat(mcvaldict_t* dict, unsigned int ix, void* value);
TMPSTATIC int mc_valdict_count(mcvaldict_t* dict);
TMPUNUSED bool mc_valdict_removebykey(mcvaldict_t* dict, void* key);
TMPSTATIC void mc_valdict_clear(mcvaldict_t* dict);
TMPSTATIC unsigned int mc_valdict_getcellindex(mcvaldict_t* dict, void* key, unsigned long hash, bool* outfound);
TMPSEMISTATIC bool mc_valdict_growandrehash(mcvaldict_t* dict);
TMPSTATIC bool mc_valdict_setkeyat(mcvaldict_t* dict, unsigned int ix, void* key);
TMPSTATIC bool mc_valdict_keysareequal(mcvaldict_t* dict, void* a, void* b);
TMPSTATIC unsigned long mc_valdict_hashkey(mcvaldict_t* dict, void* key);
TMPSTATIC mcbasicarray_t* mc_basicarray_make(mcstate_t* state, size_t tsz);
TMPSTATIC mcbasicarray_t* mc_basicarray_makecapacity(mcstate_t* state, unsigned int capacity, size_t tsz);
TMPSTATIC void mc_basicarray_destroy(mcbasicarray_t* arr);
TMPSTATIC mcbasicarray_t* mc_basicarray_copy(mcbasicarray_t* arr);
TMPSTATIC bool mc_basicarray_push(mcbasicarray_t* arr, void* value);
TMPUNUSED bool mc_basicarray_addn(mcbasicarray_t* arr, void* values, int n);
TMPUNUSED bool mc_basicarray_addarray(mcbasicarray_t* dest, mcbasicarray_t* source);
TMPSTATIC bool mc_basicarray_pop(mcbasicarray_t* arr, void* outvalue);
TMPSTATIC void* mc_basicarray_top(mcbasicarray_t* arr);
TMPSTATIC bool mc_basicarray_set(mcbasicarray_t* arr, unsigned int ix, void* value);
TMPUNUSED bool mc_basicarray_setn(mcbasicarray_t* arr, unsigned int ix, void* values, int n);
TMPSTATIC MCINLINE void* mc_basicarray_get(mcbasicarray_t* arr, unsigned int ix);
TMPSTATIC MCINLINE void* mc_basicarray_getconst(mcbasicarray_t* arr, unsigned int ix);
TMPSTATIC MCINLINE int mc_basicarray_count(mcbasicarray_t* arr);
TMPUNUSED MCINLINE unsigned int mc_basicarray_getcapacity(mcbasicarray_t* arr);
TMPSTATIC bool mc_basicarray_removeat(mcbasicarray_t* arr, unsigned int ix);
TMPSTATIC bool mc_basicarray_removeitem(mcbasicarray_t* arr, void* ptr);
TMPSTATIC void mc_basicarray_clear(mcbasicarray_t* arr);
TMPUNUSED void mc_basicarray_clearanddeinititems(mcbasicarray_t* arr, mcitemdeinitfn_t deinit_fn);
TMPSTATIC void mc_basicarray_lockcapacity(mcbasicarray_t* arr);
TMPSTATIC int mc_basicarray_getindex(mcbasicarray_t* arr, void* ptr);
TMPSTATIC bool mc_basicarray_contains(mcbasicarray_t* arr, void* ptr);
TMPSTATIC void* mc_basicarray_data(mcbasicarray_t* arr);
TMPUNUSED void* mc_basicarray_constdata(mcbasicarray_t* arr);
TMPSTATIC void mc_basicarray_orphandata(mcbasicarray_t* arr);
TMPSTATIC bool mc_basicarray_reverse(mcbasicarray_t* arr);
TMPSTATIC bool mc_basicarray_initcapacity(mcbasicarray_t* arr, mcstate_t* state, unsigned int capacity, size_t tsz);
TMPSTATIC void mc_basicarray_deinit(mcbasicarray_t* arr);
TMPSTATIC mcptrarray_t* mc_ptrarray_make(mcstate_t* state);
TMPSTATIC mcptrarray_t* mc_ptrarray_makecapacity(mcstate_t* state, unsigned int capacity);
TMPSTATIC void mc_ptrarray_destroy(mcptrarray_t* arr, mcitemdestroyfn_t dfn);
TMPSTATIC mcptrarray_t* mc_ptrarray_copy(mcptrarray_t* arr, mcitemcopyfn_t copyfn, mcitemdestroyfn_t dfn);
TMPSTATIC bool mc_ptrarray_push(mcptrarray_t* arr, void* ptr);
TMPSTATIC void* mc_ptrarray_get(mcptrarray_t* arr, unsigned int ix);
TMPSTATIC void* mc_ptrarray_pop(mcptrarray_t* arr);
TMPSTATIC void* mc_ptrarray_top(mcptrarray_t* arr);
TMPSTATIC int mc_ptrarray_count(mcptrarray_t* arr);
TMPSTATIC bool mc_ptrarray_removeat(mcptrarray_t* arr, unsigned int ix);
TMPSTATIC void mc_ptrarray_clear(mcptrarray_t* arr);
TMPSTATIC void mc_ptrarray_clearanddestroy(mcptrarray_t* arr, mcitemdestroyfn_t dfn);
TMPUNUSED void mc_ptrarray_lockcapacity(mcptrarray_t* arr);
TMPSTATIC int mc_ptrarray_getindex(mcptrarray_t* arr, void* ptr);
TMPUNUSED bool mc_ptrarray_contains(mcptrarray_t* arr, void* item);
TMPUNUSED void* mc_ptrarray_getaddr(mcptrarray_t* arr, unsigned int ix);
TMPUNUSED void* mc_ptrarray_data(mcptrarray_t* arr);
TMPUNUSED void mc_ptrarray_reverse(mcptrarray_t* arr);
TMPSTATIC mcprinter_t* mc_printer_make(mcstate_t* state, FILE* ofh);
TMPSTATIC bool mc_printer_init(mcprinter_t* pr, mcstate_t* state, size_t capacity, FILE* ofh, bool onstack);
TMPSTATIC mcprinter_t* mc_printer_make_with_capacity(mcstate_t* state, unsigned int capacity, FILE* ofh);
TMPSTATIC void mc_printer_destroy(mcprinter_t* pr);
TMPUNUSED void mc_printer_clear(mcprinter_t* pr);
TMPSTATIC bool mc_printer_putlen(mcprinter_t* pr, const char* str, size_t len);
TMPSTATIC bool mc_printer_puts(mcprinter_t* pr, const char* str);
TMPSTATIC bool mc_printer_putchar(mcprinter_t* pr, int b);
TMPSEMISTATIC bool mc_printer_printf(mcprinter_t* pr, const char* fmt, ...);
void mc_printer_printescapedchar(mcprinter_t* pr, int ch);
void mc_printer_printescapedstring(mcprinter_t* pr, const char* str, size_t len);
TMPSTATIC const char* mc_printer_getstring(mcprinter_t* pr);
TMPUNUSED size_t mc_printer_getlength(mcprinter_t* pr);
TMPSTATIC char* mc_printer_getstringanddestroy(mcprinter_t* pr, size_t* lendest);
TMPSTATIC bool mc_printer_failed(mcprinter_t* pr);
TMPSTATIC bool mc_printer_grow(mcprinter_t* pr, size_t newcapacity);
TMPSEMISTATIC void mc_printer_printobject_actual(int vt, mcprinter_t* pr, mcvalue_t obj);
TMPSTATIC mcastlocation_t mc_astlocation_make(mcastcompiledfile_t* file, int line, int column);
TMPSEMISTATIC char* mc_util_stringallocfmt(mcstate_t* state, const char* format, ...);
TMPSTATIC uint64_t mc_util_doubletouint64(mcfloat_t val);
TMPSTATIC mcfloat_t mc_util_uint64todouble(uint64_t val);
TMPSTATIC void mc_errlist_init(mcerrlist_t* errors);
TMPSTATIC void mc_errlist_deinit(mcerrlist_t* errors);
TMPSTATIC void mc_errlist_push(mcerrlist_t* errors, mcerrtype_t type, mcastlocation_t pos, const char* message);
TMPSEMISTATIC void mc_errlist_addfv(mcerrlist_t* errors, mcerrtype_t type, mcastlocation_t pos, const char* format, va_list va);
TMPSEMISTATIC void mc_errlist_addf(mcerrlist_t* errors, mcerrtype_t type, mcastlocation_t pos, const char* format, ...);
TMPSTATIC void mc_errlist_clear(mcerrlist_t* errors);
TMPSTATIC mcerror_t* mc_errlist_get(mcerrlist_t* errors, int ix);
TMPUNUSED const char* mc_util_errtypename(mcerrtype_t type);
TMPSTATIC mcerror_t* mc_errlist_getlast(mcerrlist_t* errors);
TMPSTATIC mcvalue_t mc_object_makedatafrom(mcvaltype_t type, mcobjdata_t* data);
TMPSTATIC mcvalue_t mc_value_makeempty(mcvaltype_t t);
TMPSTATIC mcvalue_t mc_value_makenumber(mcfloat_t val);
TMPSTATIC mcvalue_t mc_value_makebool(bool val);
TMPSTATIC mcvalue_t mc_value_makenull(void);
TMPSTATIC mcvalue_t mc_value_makestrcapacity(mcstate_t* state, int capacity);
TMPUNUSED mcvalue_t mc_value_makestrformat(mcstate_t* state, const char* fmt, ...);
TMPSTATIC mcvalue_t mc_value_makestringlen(mcstate_t* state, const char* string, size_t len);
TMPSTATIC mcvalue_t mc_value_makestring(mcstate_t* state, const char* string);
TMPSTATIC mcvalue_t mc_value_makefuncnative(mcstate_t* state, const char* name, mcnativefn_t fn, void* data, int dlen);
TMPSTATIC mcvalue_t mc_value_makearray(mcstate_t* state);
TMPSTATIC mcvalue_t mc_value_makearraycapacity(mcstate_t* state, unsigned capacity);
TMPSTATIC mcvalue_t mc_value_makemap(mcstate_t* state);
TMPSTATIC mcvalue_t mc_value_makemapcapacity(mcstate_t* state, unsigned capacity);
TMPSTATIC mcvalue_t mc_value_makeerror(mcstate_t* state, const char* error);
TMPSTATIC mcvalue_t mc_value_makeerrornocopy(mcstate_t* state, char* error);
TMPUNUSED mcvalue_t mc_value_makeerrorf(mcstate_t* state, const char* fmt, ...);
TMPSTATIC mcvalue_t mc_value_makefuncscript(mcstate_t* state, const char* name, mccompiledprogram_t* cres, bool ownsdt, int nlocals, int nargs, int fvc);
TMPSTATIC mcvalue_t mc_value_makeuserobject(mcstate_t* state, void* data);
TMPUNUSED void mc_value_deinit(mcvalue_t obj);
TMPSTATIC void mc_objectdata_deinit(mcobjdata_t* data);
TMPSTATIC bool mc_value_isallocated(mcvalue_t object);
TMPUNUSED mcgcmemory_t* mc_value_getmem(mcvalue_t obj);
TMPSTATIC const char* mc_valtype_getname(mcvaltype_t type);
TMPSTATIC char* mc_valtype_getunionname(mcstate_t* state, mcvaltype_t type);
TMPSTATIC mcvalue_t mc_value_copydeep(mcstate_t* state, mcvalue_t obj);
TMPSTATIC mcvalue_t mc_value_copyflat(mcstate_t* state, mcvalue_t obj);
TMPSTATIC bool mc_value_compare(mcvalue_t a, mcvalue_t b, mcvalcmpresult_t* cres);
TMPSTATIC bool mc_value_equals(mcvalue_t a, mcvalue_t b);
TMPSTATIC mcobjuserdata_t* mc_valuserobject_getdata(mcvalue_t object);
TMPSTATIC bool mc_valuserobject_setdestroyfunction(mcvalue_t object, mcitemdestroyfn_t dfn);
TMPSTATIC bool mc_value_getbool(mcvalue_t obj);
TMPSTATIC mcfloat_t mc_value_getnumber(mcvalue_t obj);
TMPSTATIC MCINLINE const char* mc_valstring_getdata(mcvalue_t object);
TMPSTATIC int mc_valstring_getlength(mcvalue_t object);
TMPSTATIC void mc_string_setlength(mcvalue_t object, int len);
TMPUNUSED int mc_valstring_getcapacity(mcvalue_t object);
TMPSTATIC MCINLINE char* mc_valstring_getmutabledata(mcvalue_t object);
TMPSTATIC bool mc_valstring_append(mcvalue_t obj, const char* src, int len);
TMPSTATIC unsigned long mc_valstring_gethash(mcvalue_t obj);
TMPSTATIC mcobjfuncscript_t* mc_value_functiongetscriptfunction(mcvalue_t object);
TMPSTATIC MCINLINE mcobjfuncnative_t* mc_value_functiongetnativefunction(mcvalue_t obj);
TMPSTATIC const char* mc_value_functiongetname(mcvalue_t obj);
TMPSTATIC mcvalue_t mc_value_functiongetfreevalat(mcvalue_t obj, int ix);
TMPSTATIC void mc_value_functionsetfreevalat(mcvalue_t obj, int ix, mcvalue_t val);
TMPUNUSED mcvalue_t* mc_value_functiongetfreevals(mcvalue_t obj);
TMPSTATIC const char* mc_value_errorgetmessage(mcvalue_t object);
TMPSTATIC void mc_value_errorsettraceback(mcvalue_t object, mctraceback_t* traceback);
TMPSTATIC mctraceback_t* mc_value_errorgettraceback(mcvalue_t object);
TMPSTATIC bool mc_valuserobject_setdata(mcvalue_t object, void* extdata);
TMPSTATIC bool mc_valuserobject_setcopyfunction(mcvalue_t object, mcitemcopyfn_t copyfn);
TMPSTATIC mcvalue_t mc_valarray_getvalueat(mcvalue_t object, int ix);
TMPSTATIC bool mc_valarray_setvalueat(mcvalue_t object, int ix, mcvalue_t val);
TMPSTATIC bool mc_valarray_push(mcvalue_t object, mcvalue_t val);
TMPSTATIC int mc_valarray_getlength(mcvalue_t object);
TMPSTATIC mcvalue_t mc_valarray_pop(mcvalue_t object);
TMPSTATIC bool mc_valarray_removevalueat(mcvalue_t object, int ix);
TMPSTATIC int mc_valmap_getlength(mcvalue_t object);
TMPSTATIC mcvalue_t mc_valmap_getkeyat(mcvalue_t object, int ix);
TMPSTATIC mcvalue_t mc_valmap_getvalueat(mcvalue_t object, int ix);
TMPUNUSED bool mc_valmap_setvalueat(mcvalue_t object, int ix, mcvalue_t val);
TMPSTATIC mcvalue_t mc_valmap_getkvpairat(mcstate_t* state, mcvalue_t object, int ix);
TMPSTATIC bool mc_valmap_setvalue(mcvalue_t object, mcvalue_t key, mcvalue_t val);
TMPSTATIC bool mc_valmap_setvalstring(mcvalue_t object, const char* strkey, mcvalue_t val);
TMPSTATIC mcvalue_t mc_valmap_getvalue(mcvalue_t object, mcvalue_t key);
TMPUNUSED bool mc_valmap_haskey(mcvalue_t object, mcvalue_t key);
TMPSEMISTATIC mcvalue_t mc_value_copydeepfuncscript(mcstate_t* state, mcvalue_t obj, mcvaldict_t* copies);
TMPSEMISTATIC mcvalue_t mc_value_copydeeparray(mcstate_t* state, mcvalue_t obj, mcvaldict_t* copies);
TMPSEMISTATIC mcvalue_t mc_value_copydeepmap(mcstate_t* state, mcvalue_t obj, mcvaldict_t* copies);
TMPSEMISTATIC mcvalue_t mc_value_copydeepintern(mcstate_t* state, mcvalue_t obj, mcvaldict_t* copies);
TMPSTATIC bool mc_value_equalswrapped(mcvalue_t* aptr, mcvalue_t* bptr);
TMPSTATIC unsigned long mc_value_hash(mcvalue_t* objptr);
TMPSTATIC mcbasicarray_t* mc_valarray_getinternalarray(mcvalue_t object);
TMPSTATIC bool mc_value_isnumber(mcvalue_t o);
TMPSTATIC bool mc_objfunction_freevalsareallocated(mcobjfuncscript_t* fun);
TMPSTATIC MCINLINE char* mc_valstring_getdataintern(mcvalue_t object);
TMPSTATIC bool mc_valstring_reservecapacity(mcobjdata_t* data, int capacity);
TMPSTATIC mcastscopecomp_t* mc_astcompscope_make(mcstate_t* state, mcastscopecomp_t* outer);
TMPSTATIC void mc_astcompscope_destroy(mcastscopecomp_t* scope);
TMPSTATIC mccompiledprogram_t* mc_astcompscope_orphanresult(mcastscopecomp_t* scope);
TMPSTATIC mccompiledprogram_t* mc_astcompresult_make(mcstate_t* state, uint8_t* bytecode, mcastlocation_t* srcposlist, int count);
TMPSTATIC void mc_astcompresult_destroy(mccompiledprogram_t* res);
TMPSTATIC bool mc_lexer_init(mcastlexer_t* lex, mcstate_t* state, mcerrlist_t* errs, const char* input, mcastcompiledfile_t* file);
TMPSTATIC bool mc_lexer_failed(mcastlexer_t* lex);
TMPSTATIC void mc_lexer_conttplstring(mcastlexer_t* lex);
TMPSTATIC bool mc_lexer_currtokenis(mcastlexer_t* lex, mcasttoktype_t type);
TMPSTATIC bool mc_lexer_peektokenis(mcastlexer_t* lex, mcasttoktype_t type);
TMPSTATIC bool mc_lexer_nexttoken(mcastlexer_t* lex);
TMPSTATIC bool mc_lexer_previoustoken(mcastlexer_t* lex);
TMPSTATIC mcasttoken_t mc_lexer_nexttokinternal(mcastlexer_t* lex);
TMPSTATIC bool mc_lexer_expectcurrent(mcastlexer_t* lex, mcasttoktype_t type);
TMPSTATIC bool mc_lexer_readchar(mcastlexer_t* lex);
TMPSTATIC char mc_lexer_peekchar(mcastlexer_t* lex);
TMPSTATIC bool mc_lexer_charisletter(char ch);
TMPSTATIC bool mc_lexer_charisdigit(char ch);
TMPSTATIC bool mc_lexer_charisoneof(char ch, const char* allowed, int allowedlen);
TMPSTATIC const char* mc_lexer_scanident(mcastlexer_t* lex, int* outlen);
TMPSTATIC const char* mc_lexer_scannumber(mcastlexer_t* lex, int* outlen);
TMPSTATIC const char* mc_lexer_scanstring(mcastlexer_t* lex, char delimiter, bool istemplate, bool* outtemplatefound, int* outlen);
TMPSTATIC mcasttoktype_t mc_lexer_lookupident(const char* ident, int len);
TMPSTATIC void mc_lexer_skipspace(mcastlexer_t* lex);
TMPSTATIC bool mc_lexer_addline(mcastlexer_t* lex, int offset);
TMPSTATIC mcastcompiledfile_t* mc_compiledfile_make(mcstate_t* state, const char* path);
TMPSTATIC void mc_compiledfile_destroy(mcastcompiledfile_t* file);
TMPSTATIC mcastcompiler_t* mc_compiler_make(mcstate_t* state, mcconfig_t* config, mcgcmemory_t* mem, mcerrlist_t* errors, mcptrarray_t* files, mcglobalstore_t* gstore);
TMPSTATIC void mc_compiler_destroy(mcastcompiler_t* comp);
TMPSTATIC mccompiledprogram_t* mc_compiler_compilesource(mcastcompiler_t* comp, const char* code);
TMPSTATIC mcastsymtable_t* mc_compiler_getsymtable(mcastcompiler_t* comp);
TMPSTATIC void mc_compiler_setsymtable(mcastcompiler_t* comp, mcastsymtable_t* table);
TMPSTATIC mcbasicarray_t* mc_compiler_getconstants(mcastcompiler_t* comp);
TMPSTATIC bool mc_compiler_init(mcastcompiler_t* comp, mcstate_t* state, mcconfig_t* cfg, mcgcmemory_t* mem, mcerrlist_t* errors, mcptrarray_t* files, mcglobalstore_t* gstor);
TMPSTATIC void mc_compiler_deinit(mcastcompiler_t* comp);
TMPSTATIC bool mc_compiler_initshallowcopy(mcastcompiler_t* copy, mcastcompiler_t* src);
mcopdefinition_t* mc_parser_makedef(mcopdefinition_t* dest, const char* name, int numop, int opa1, int opa2);
TMPSTATIC mcopdefinition_t* mc_opdef_lookup(mcinternopcode_t op);
TMPSTATIC const char* mc_opdef_getname(mcinternopcode_t op);
TMPSTATIC mcastexpression_t* mc_astexpr_makeident(mcstate_t* state, mcastident_t* ident);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralnumber(mcstate_t* state, mcfloat_t val);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralbool(mcstate_t* state, bool val);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralstring(mcstate_t* state, char* value, size_t len);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralnull(mcstate_t* state);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralarray(mcstate_t* state, mcptrarray_t* values);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralmap(mcstate_t* state, mcptrarray_t* keys, mcptrarray_t* values);
TMPSTATIC mcastexpression_t* mc_astexpr_makeprefixexpr(mcstate_t* state, mcastmathoptype_t op, mcastexpression_t* right);
TMPSTATIC mcastexpression_t* mc_astexpr_makeinfixexpr(mcstate_t* state, mcastmathoptype_t op, mcastexpression_t* left, mcastexpression_t* right);
TMPSTATIC mcastexpression_t* mc_astexpr_makeliteralfunction(mcstate_t* state, mcptrarray_t* params, mcastcodeblock_t* body);
TMPSTATIC mcastexpression_t* mc_astexpr_makecallexpr(mcstate_t* state, mcastexpression_t* function, mcptrarray_t* args);
TMPSTATIC mcastexpression_t* mc_astexpr_makeindexexpr(mcstate_t* state, mcastexpression_t* left, mcastexpression_t* index, bool isdot);
TMPSTATIC mcastexpression_t* mc_astexpr_makeassignexpr(mcstate_t* state, mcastexpression_t* dest, mcastexpression_t* source, bool is_postfix);
TMPSTATIC mcastexpression_t* mc_astexpr_makelogicalexpr(mcstate_t* state, mcastmathoptype_t op, mcastexpression_t* left, mcastexpression_t* right);
TMPSTATIC mcastexpression_t* mc_astexpr_maketernaryexpr(mcstate_t* state, mcastexpression_t* test, mcastexpression_t* ift, mcastexpression_t* iffalse);
TMPSEMISTATIC void mc_astexpr_destroy(mcastexpression_t* expr);
TMPSEMISTATIC mcastexpression_t* mc_astexpr_copy(mcastexpression_t* expr);
TMPSTATIC mcastexpression_t* mc_astexpr_makedefineexpr(mcstate_t* state, mcastident_t* name, mcastexpression_t* value, bool assignable);
TMPSTATIC mcastexpression_t* mc_astexpr_makeifexpr(mcstate_t* state, mcptrarray_t* cases, mcastcodeblock_t* alternative);
TMPSTATIC mcastexpression_t* mc_astexpr_makereturnexpr(mcstate_t* state, mcastexpression_t* value);
TMPSTATIC mcastexpression_t* mc_astexpr_makeexprstmt(mcstate_t* state, mcastexpression_t* value);
TMPSTATIC mcastexpression_t* mc_astexpr_makewhileexpr(mcstate_t* state, mcastexpression_t* test, mcastcodeblock_t* body);
TMPSTATIC mcastexpression_t* mc_astexpr_makebreakexpr(mcstate_t* state);
TMPSTATIC mcastexpression_t* mc_astexpr_makeforeachexpr(mcstate_t* state, mcastident_t* iterator, mcastexpression_t* source, mcastcodeblock_t* body);
TMPSTATIC mcastexpression_t* mc_astexpr_makeforloopexpr(mcstate_t* state, mcastexpression_t* init, mcastexpression_t* test, mcastexpression_t* update, mcastcodeblock_t* body);
TMPSTATIC mcastexpression_t* mc_astexpr_makecontinueexpr(mcstate_t* state);
TMPSTATIC mcastexpression_t* mc_astexpr_makeblockexpr(mcstate_t* state, mcastcodeblock_t* block);
TMPSTATIC mcastexpression_t* mc_astexpr_makeimportexpr(mcstate_t* state, char* path);
TMPSTATIC mcastexpression_t* mc_astexpr_makerecoverexpr(mcstate_t* state, mcastident_t* eid, mcastcodeblock_t* body);
TMPSTATIC mcastcodeblock_t* mc_astcodeblock_make(mcstate_t* state, mcptrarray_t* statements);
TMPSTATIC void mc_astcodeblock_destroy(mcastcodeblock_t* block);
TMPSTATIC mcastcodeblock_t* mc_astcodeblock_copy(mcastcodeblock_t* block);
TMPSTATIC mcastfuncparam_t* mc_astfuncparam_make(mcstate_t* state, mcastident_t* ident);
TMPSTATIC mcastfuncparam_t* mc_astfuncparam_copy(mcastfuncparam_t* param);
TMPSTATIC void mc_astfuncparam_destroy(mcastfuncparam_t* param);
TMPSTATIC mcastident_t* mc_astident_make(mcstate_t* state, mcasttoken_t tok);
TMPSTATIC mcastident_t* mc_astident_copy(mcastident_t* ident);
TMPSTATIC void mc_astident_destroy(mcastident_t* ident);
TMPSTATIC mcastifcase_t* mc_astifcase_make(mcstate_t* state, mcastexpression_t* test, mcastcodeblock_t* consequence);
TMPSTATIC void mc_astifcase_destroy(mcastifcase_t* cond);
TMPSTATIC mcastifcase_t* mc_astifcase_copy(mcastifcase_t* ifcase);
TMPSTATIC mcastexpression_t* mc_astexpr_makeexpression(mcstate_t* state, mcastexprtype_t type);
TMPSTATIC mcastparser_t* mc_astparser_make(mcstate_t* state, mcconfig_t* config, mcerrlist_t* errors);
TMPSTATIC void mc_astparser_destroy(mcastparser_t* parser);
TMPSTATIC mcptrarray_t* mc_astparser_parseall(mcastparser_t* parser, const char* input, mcastcompiledfile_t* file);
TMPSTATIC mcastexpression_t* mc_astparser_parsestatement(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parsevarletstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parseifstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parsereturnstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parseexprstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parseloopwhilestmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parsebreakstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parsecontinuestmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parseblockstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parseimportstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parserecoverstmt(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parseloopforstmt(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseloopforeachstmt(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseloopforclassicstmt(mcastparser_t* p);
TMPSTATIC mcastcodeblock_t* mc_parser_parsecodeblock(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseexpression(mcastparser_t* p, mcastprecedence_t prec);
TMPSTATIC mcastexpression_t* mc_parser_parseident(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralnumber(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralbool(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralstring(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteraltemplatestring(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralnull(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralarray(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralmap(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseprefixexpr(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseinfixexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastexpression_t* mc_parser_parsegroupedexpr(mcastparser_t* p);
TMPSTATIC bool mc_parser_parsefuncparams(mcastparser_t* p, mcptrarray_t* outparams);
TMPSTATIC mcastexpression_t* mc_parser_parseliteralfunction(mcastparser_t* p);
TMPSEMISTATIC mcastexpression_t* mc_parser_parsefunctionstmt(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parsecallexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcptrarray_t* mc_parser_parseexprlist(mcastparser_t* p, mcasttoktype_t starttoken, mcasttoktype_t endtoken, bool trailingcommaallowed);
TMPSTATIC mcastexpression_t* mc_parser_parseindexexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastexpression_t* mc_parser_parseassignexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastexpression_t* mc_parser_parselogicalexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastexpression_t* mc_parser_parseternaryexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastexpression_t* mc_parser_parseincdecprefixexpr(mcastparser_t* p);
TMPSTATIC mcastexpression_t* mc_parser_parseincdecpostfixexpr(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastexpression_t* mc_parser_parsedotexpression(mcastparser_t* p, mcastexpression_t* left);
TMPSTATIC mcastprecedence_t mc_parser_getprecedence(mcasttoktype_t tk);
TMPSTATIC mcastmathoptype_t mc_parser_tokentomathop(mcasttoktype_t tk);
TMPSTATIC char mc_parser_getescapechar(char c);
TMPSTATIC char* mc_parser_processandcopystring(mcstate_t* state, const char* input, size_t len);
TMPSTATIC mcastexpression_t* mc_parser_makefunccallexpr(mcstate_t* state, mcastexpression_t* expr, const char* fname);
TMPSEMISTATIC mcastexpression_t* mc_optimizer_optexpression(mcastexpression_t* expr);
TMPSTATIC mcastexpression_t* mc_optimizer_optinfixexpr(mcastexpression_t* expr);
TMPSTATIC mcastexpression_t* mc_optimizer_optprefixexpr(mcastexpression_t* expr);
TMPSTATIC int mc_compiler_gencode(mcinternopcode_t op, int operandscount, const uint64_t* operands, mcbasicarray_t* res);
TMPSTATIC int mc_compiler_emit(mcastcompiler_t* comp, mcinternopcode_t op, int operandscount, uint64_t* operands);
TMPSTATIC mcastscopecomp_t* mc_compiler_getcompilationscope(mcastcompiler_t* comp);
TMPSTATIC bool mc_compiler_pushcompilationscope(mcastcompiler_t* comp);
TMPSTATIC void mc_compiler_popcompilationscope(mcastcompiler_t* comp);
TMPSTATIC bool mc_compiler_pushsymtable(mcastcompiler_t* comp, int globaloffset);
TMPSTATIC void mc_compiler_popsymtable(mcastcompiler_t* comp);
TMPSTATIC mcinternopcode_t mc_compiler_getlastopcode(mcastcompiler_t* comp);
TMPSTATIC bool mc_compiler_docompilesource(mcastcompiler_t* comp, const char* code);
TMPSEMISTATIC bool mc_compiler_compilestmtlist(mcastcompiler_t* comp, mcptrarray_t* statements);
TMPSTATIC bool mc_compiler_compileimport(mcastcompiler_t* comp, mcastexpression_t* importstmt);
TMPSEMISTATIC bool mc_compiler_compilestatement(mcastcompiler_t* comp, mcastexpression_t* expr);
TMPSEMISTATIC bool mc_compiler_compileexpression(mcastcompiler_t* comp, mcastexpression_t* expr);
TMPSEMISTATIC bool mc_compiler_compilecodeblock(mcastcompiler_t* comp, mcastcodeblock_t* block);
TMPSTATIC int mc_compiler_addconstant(mcastcompiler_t* comp, mcvalue_t obj);
TMPSTATIC void mc_compiler_changeuint16operand(mcastcompiler_t* comp, int ip, uint16_t operand);
TMPSTATIC bool mc_compiler_lastopcodeis(mcastcompiler_t* comp, mcinternopcode_t op);
TMPSTATIC bool mc_compiler_readsymbol(mcastcompiler_t* comp, mcastsymbol_t* symbol);
TMPSTATIC bool mc_compiler_storesymbol(mcastcompiler_t* comp, mcastsymbol_t* symbol, bool define);
TMPSTATIC bool mc_compiler_pushbreakip(mcastcompiler_t* comp, int ip);
TMPSTATIC void mc_compiler_popbreakip(mcastcompiler_t* comp);
TMPSTATIC int mc_compiler_getbreakip(mcastcompiler_t* comp);
TMPSTATIC bool mc_compiler_pushcontinueip(mcastcompiler_t* comp, int ip);
TMPSTATIC void mc_compiler_popcontinueip(mcastcompiler_t* comp);
TMPSTATIC int mc_compiler_getcontinueip(mcastcompiler_t* comp);
TMPSTATIC int mc_compiler_getip(mcastcompiler_t* comp);
TMPSTATIC mcbasicarray_t* mc_compiler_getsrcpositions(mcastcompiler_t* comp);
TMPSTATIC mcbasicarray_t* mc_compiler_getbytecode(mcastcompiler_t* comp);
TMPSTATIC mcastscopefile_t* mc_compiler_filescopemake(mcastcompiler_t* comp, mcastcompiledfile_t* file);
TMPSTATIC void mc_compiler_filescopedestroy(mcastscopefile_t* scope);
TMPSTATIC bool mc_compiler_filescopepush(mcastcompiler_t* comp, const char* filepath);
TMPSTATIC void mc_compiler_filescopepop(mcastcompiler_t* comp);
TMPSTATIC void mc_compiler_setcompilationscope(mcastcompiler_t* comp, mcastscopecomp_t* scope);
TMPSTATIC module_t* mc_module_make(mcstate_t* state, const char* name);
TMPSTATIC const char* mc_module_findfile(mcstate_t* state, const char* filename);
TMPSTATIC void mc_module_destroy(module_t* module);
TMPSTATIC module_t* mc_module_copy(module_t* src);
TMPSTATIC const char* mc_util_getmodulename(const char* path);
TMPSTATIC bool mc_module_addsymbol(module_t* module, mcastsymbol_t* symbol);
TMPSTATIC mcastsymbol_t* mc_compiler_defsymbol(mcastcompiler_t* comp, mcastlocation_t pos, const char* name, bool assignable, bool canshadow);
TMPSTATIC mcstate_t* mc_state_make(void);
TMPSTATIC void mc_state_deinit(mcstate_t* state);
TMPSTATIC void mc_state_reset(mcstate_t* state);
TMPSTATIC void mc_state_setdefaultconfig(mcstate_t* state);
TMPSTATIC void mc_state_destroy(mcstate_t* state);
TMPSTATIC void mc_state_freeallocated(mcstate_t* state, void* ptr);
TMPSTATIC void mc_state_printerrors(mcstate_t* state);
TMPSTATIC mccompiledprogram_t* mc_state_compilesource(mcstate_t* state, const char* code);
TMPSTATIC mcvalue_t mc_program_execute(mcstate_t* state, mccompiledprogram_t* program);
TMPSTATIC void mc_program_destroy(mccompiledprogram_t* program);
TMPUNUSED mcvalue_t mc_state_execcode(mcstate_t* state, const char* code);
TMPUNUSED mcvalue_t mc_state_callfunctionbyname(mcstate_t* state, const char* fname, int argc, mcvalue_t* args);
TMPSTATIC bool mc_state_haserrors(mcstate_t* state);
TMPSTATIC int mc_state_errorcount(mcstate_t* state);
TMPSTATIC void mc_state_clearerrors(mcstate_t* state);
TMPSTATIC mcerror_t* mc_state_geterror(mcstate_t* state, int index);
TMPSTATIC bool mc_state_setnativefunction(mcstate_t* state, const char* name, mcnativefn_t fn, void* data, size_t dlen);
TMPSTATIC bool mc_state_setglobalconstant(mcstate_t* state, const char* name, mcvalue_t obj);
TMPSTATIC mcvalue_t mc_state_getglobalobjectbyname(mcstate_t* state, const char* name);
TMPSTATIC void mc_state_pusherrorfv(mcstate_t* state, mcerrtype_t type, mcastlocation_t pos, const char* fmt, va_list va);
TMPSEMISTATIC void mc_state_pusherrorf(mcstate_t* state, mcerrtype_t type, mcastlocation_t pos, const char* fmt, ...);
static void mc_state_complainv(mcstate_t *state, mcastlocation_t pos, const char *fmt, va_list va);
static void mc_state_complain(mcstate_t *state, mcastlocation_t pos, const char *fmt, ...);
TMPSEMISTATIC void mc_state_setruntimeerrorf(mcstate_t* state, const char* fmt, ...);
TMPSTATIC bool mc_value_isnumeric(mcvalue_t obj);
TMPSTATIC bool mc_value_isnull(mcvalue_t obj);
TMPSTATIC bool mc_value_iscallable(mcvalue_t obj);
TMPSTATIC const char* mc_util_objtypename(mcvaltype_t type);
TMPSTATIC const char* mc_error_getmessage(mcerror_t* error);
TMPSTATIC const char* mc_error_getfilepath(mcerror_t* error);
TMPSTATIC const char* mc_error_getsourcelinecode(mcerror_t* error);
TMPSTATIC int mc_error_getsourcelinenumber(mcerror_t* error);
TMPSTATIC int mc_error_getsourcecolumn(mcerror_t* error);
TMPSTATIC mcerrtype_t mc_error_gettype(mcerror_t* error);
TMPSTATIC const char* mc_error_gettypestring(mcerror_t* error);
TMPSTATIC const char* mc_util_errortypename(mcerrtype_t type);
TMPSTATIC char* mc_error_serializetostring(mcstate_t* state, mcerror_t* err);
TMPSTATIC mctraceback_t* mc_error_gettraceback(mcerror_t* error);
TMPUNUSED int mc_traceback_getdepth(mctraceback_t* traceback);
TMPUNUSED const char* mc_traceback_getsourcefilepath(mctraceback_t* traceback, int depth);
TMPUNUSED const char* mc_traceback_getsourcelinecode(mctraceback_t* traceback, int depth);
TMPUNUSED int mc_traceback_getsourcelinenumber(mctraceback_t* traceback, int depth);
TMPUNUSED int mc_traceback_getsourcecolumn(mctraceback_t* traceback, int depth);
TMPUNUSED const char* mc_traceback_getfunctionname(mctraceback_t* traceback, int depth);
TMPSTATIC void mc_astprint_stmtlist(mcprinter_t* pr, mcptrarray_t* statements);
TMPSEMISTATIC void mc_astprint_expression(mcprinter_t* pr, mcastexpression_t* expr);
TMPSTATIC void mc_astprint_codeblock(mcprinter_t* pr, mcastcodeblock_t* expr);
TMPSTATIC const char* mc_util_mathopstring(mcastmathoptype_t op);
TMPUNUSED bool mc_argcheck_checkactual(mcstate_t* state, bool generateerror, int argc, mcvalue_t* args, int expectedargc, const mcvaltype_t* expectedtypes);
TMPUNUSED mcvalue_t mc_scriptfn_binnot(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPUNUSED mcvalue_t mc_scriptfn_ord(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPUNUSED mcvalue_t mc_scriptfn_arrayjoin(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_index(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_left(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_right(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_replace(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_replacefirst(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_trim(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_lengthof(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_typeof(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_arrayfirst(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_arraylast(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_arrayrest(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_reverse(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_array(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_arraypush(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_arraypop(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_externalfn(mcstate_t* state, void *data, int argc, mcvalue_t *args);
TMPSTATIC mcvalue_t mc_scriptfn_vec2add(mcstate_t *state, void *data, int argc, mcvalue_t *args);
TMPSTATIC mcvalue_t mc_scriptfn_vec2sub(mcstate_t *state, void *data, int argc, mcvalue_t *args);
TMPSTATIC mcvalue_t mc_scriptfn_testcheckargs(mcstate_t* state, void *data, int argc, mcvalue_t *args);
TMPSTATIC mcvalue_t mc_scriptfn_maketestdict(mcstate_t *state, void *data, int argc, mcvalue_t *args);
TMPSTATIC mcvalue_t mc_scriptfn_squarearray(mcstate_t *state, void *data, int argc, mcvalue_t *args);
TMPSTATIC mcvalue_t mc_scriptfn_print(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_println(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_filewritefile(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_filereadfile(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_tostring(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_jsonstringify(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_tonum(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isnan(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_chr(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_range(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_keys(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_values(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_copy(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_copydeep(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_remove(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_removeat(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_error(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_crash(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_assert(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_randseed(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_random(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_slice(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isstring(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isarray(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_ismap(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isnumber(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isbool(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isnull(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isfunction(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isexternal(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_iserror(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_isnativefunction(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_sqrt(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_pow(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_sin(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_cos(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_tan(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_log(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_ceil(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_floor(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcvalue_t mc_scriptfn_abs(mcstate_t* state, void* data, int argc, mcvalue_t* args);
TMPSTATIC mcptrarray_t* mc_util_splitstring(mcstate_t* state, const char* str, const char* delimiter);
TMPSTATIC char* mc_util_joinstringarray(mcstate_t* state, mcptrarray_t* items, const char* with);
TMPSTATIC char* mc_util_canonpath(mcstate_t* state, const char* path);
TMPSTATIC bool mc_util_pathisabsolute(const char* path);
TMPSTATIC bool mc_util_strequal(const char* a, const char* b);
TMPSTATIC MCINLINE bool mc_callframe_init(mcvmframe_t* frame, mcvalue_t functionobj, int baseptr);
TMPSTATIC MCINLINE uint64_t mc_callframe_readuint64(mcvmframe_t* frame);
TMPSTATIC MCINLINE uint16_t mc_callframe_readuint16(mcvmframe_t* frame);
TMPSTATIC MCINLINE uint8_t mc_callframe_readuint8(mcvmframe_t* frame);
TMPSTATIC MCINLINE mcopcode_t mc_callframe_readopcode(mcvmframe_t* frame);
TMPSTATIC MCINLINE mcastlocation_t mc_callframe_getpos(mcvmframe_t* frame);
TMPSTATIC mcgcmemory_t* mc_gcmemory_make(mcstate_t* state);
TMPSTATIC void mc_gcmemory_destroy(mcgcmemory_t* mem);
TMPSTATIC mcobjdata_t* mc_gcmemory_allocobjectdata(mcstate_t* state);
TMPSTATIC mcobjdata_t* mc_gcmemory_getdatafrompool(mcstate_t* state, mcvaltype_t type);
TMPSTATIC void mc_state_gcunmarkall(mcstate_t* state);
TMPSEMISTATIC void mc_state_gcmarkobjlist(mcvalue_t* objects, int count);
TMPSEMISTATIC void mc_state_gcmarkobject(mcvalue_t obj);
TMPSTATIC void mc_state_gcsweep(mcstate_t* state);
TMPUNUSED bool mc_state_gcdisablefor(mcvalue_t obj);
TMPUNUSED void mc_state_gcenablefor(mcvalue_t obj);
TMPSTATIC int mc_state_gcshouldsweep(mcstate_t* state);
TMPSTATIC mcgcobjdatapool_t* mc_state_gcgetpoolfortype(mcstate_t* state, mcvaltype_t type);
TMPSTATIC bool mc_state_gccandatabeputinpool(mcstate_t* state, mcobjdata_t* data);
TMPSTATIC mcglobalstore_t* mc_globalstore_make(mcstate_t* state);
TMPSTATIC void mc_globalstore_destroy(mcglobalstore_t* store);
TMPSTATIC mcastsymbol_t* mc_globalstore_getsymbol(mcglobalstore_t* store, const char* name);
TMPSTATIC bool mc_globalstore_setnamed(mcglobalstore_t* store, const char* name, mcvalue_t object);
TMPSTATIC mcvalue_t mc_globalstore_getatindex(mcglobalstore_t* store, int ix, bool* outok);
TMPSTATIC mcvalue_t* mc_globalstore_getdata(mcglobalstore_t* store);
TMPSTATIC int mc_globalstore_getcount(mcglobalstore_t* store);
TMPSTATIC bool mc_value_ishashable(mcvalue_t obj);
TMPSTATIC bool mc_printutil_bcreadoperands(mcopdefinition_t* def, const uint8_t* instr, uint64_t outoperands[2]);
TMPSTATIC void mc_printer_printbytecode(mcprinter_t* pr, uint8_t* code, mcastlocation_t* sposlist, size_t codesize, bool simple);
TMPSTATIC void mc_printer_printobjstring(mcprinter_t* pr, mcvalue_t obj);
TMPSTATIC void mc_printer_printobjfuncscript(mcprinter_t* pr, mcvalue_t obj);
TMPSTATIC void mc_printer_printobjarray(mcprinter_t* pr, mcvalue_t obj);
TMPSTATIC void mc_printer_printobjmap(mcprinter_t* pr, mcvalue_t obj);
TMPSTATIC void mc_printer_printobjerror(mcprinter_t* pr, mcvalue_t obj);
TMPSTATIC mcastsymbol_t* mc_symbol_make(mcstate_t* state, const char* name, mcastsymtype_t type, int index, bool assignable);
TMPSTATIC void mc_symbol_destroy(mcastsymbol_t* symbol);
TMPSTATIC mcastsymbol_t* mc_symbol_copy(mcastsymbol_t* symbol);
TMPSTATIC mcastsymtable_t* mc_symtable_make(mcstate_t* state, mcastsymtable_t* outer, mcglobalstore_t* gstore, int mgo);
TMPSTATIC void mc_symtable_destroy(mcastsymtable_t* table);
TMPSTATIC mcastsymtable_t* mc_symtable_copy(mcastsymtable_t* table);
TMPSTATIC bool mc_symtable_addmodsymbol(mcastsymtable_t* st, mcastsymbol_t* symbol);
TMPSTATIC mcastsymbol_t* mc_symtable_define(mcastsymtable_t* table, const char* name, bool assignable);
TMPSTATIC mcastsymbol_t* mc_symtable_defineanddestroyold(mcastsymtable_t* st, mcastsymbol_t* original);
TMPSTATIC mcastsymbol_t* mc_symtable_definefunctionname(mcastsymtable_t* st, const char* name, bool assignable);
TMPSTATIC mcastsymbol_t* mc_symtable_definethis(mcastsymtable_t* st);
TMPSEMISTATIC mcastsymbol_t* mc_symtable_resolve(mcastsymtable_t* table, const char* name);
TMPSTATIC bool mc_symtable_isdefined(mcastsymtable_t* table, const char* name);
TMPSTATIC bool mc_symtable_pushblockscope(mcastsymtable_t* table);
TMPSTATIC void mc_symtable_popblockscope(mcastsymtable_t* table);
TMPSTATIC mcastscopeblock_t* mc_symtable_getblockscope(mcastsymtable_t* table);
TMPSTATIC bool mc_symtable_ismodglobalscope(mcastsymtable_t* table);
TMPSTATIC bool mc_symtable_istopblockscope(mcastsymtable_t* table);
TMPSTATIC bool mc_symtable_istopglobalscope(mcastsymtable_t* table);
TMPSTATIC int mc_symtable_getmodglobalsymcount(mcastsymtable_t* table);
TMPSTATIC mcastsymbol_t* mc_symtable_getmodglobalsymat(mcastsymtable_t* table, int ix);
TMPSTATIC mcastscopeblock_t* mc_astblockscope_make(mcstate_t* state, int offset);
TMPSTATIC void mc_astblockscope_destroy(mcastscopeblock_t* scope);
TMPSTATIC mcastscopeblock_t* mc_astblockscope_copy(mcastscopeblock_t* scope);
TMPSTATIC bool mc_symtable_setsymbol(mcastsymtable_t* table, mcastsymbol_t* symbol);
TMPSTATIC int mc_symtable_nextsymindex(mcastsymtable_t* table);
TMPSTATIC int mc_symtable_getnumdefs(mcastsymtable_t* table);
TMPSTATIC void mc_asttoken_init(mcasttoken_t* tok, mcasttoktype_t type, const char* literal, int len);
TMPSTATIC char* mc_asttoken_dupliteralstring(mcstate_t* state, mcasttoken_t* tok);
TMPSTATIC const char* mc_asttoken_typename(mcasttoktype_t type);
TMPSTATIC mctraceback_t* mc_traceback_make(mcstate_t* state);
TMPSTATIC void mc_traceback_destroy(mctraceback_t* traceback);
TMPSTATIC bool mc_traceback_push(mctraceback_t* traceback, const char* fname, mcastlocation_t pos);
TMPSTATIC bool mc_traceback_vmpush(mctraceback_t* traceback, mcstate_t* state);
TMPSTATIC bool mc_printer_printtraceback(mcprinter_t* pr, mctraceback_t* traceback);
TMPSTATIC const char* mc_traceitem_getsourceline(mctraceitem_t* item);
TMPSTATIC const char* mc_traceitem_getsourcefilepath(mctraceitem_t* item);
TMPSTATIC bool mc_vm_init(mcstate_t* state);
TMPSTATIC void mc_vm_reset(mcstate_t* state);
TMPSTATIC bool mc_vm_runexecfunc(mcstate_t* state, mccompiledprogram_t* comp_res, mcbasicarray_t* constants);
TMPSTATIC mcvalue_t mc_vm_callvalue(mcstate_t* state, mcbasicarray_t* constants, mcvalue_t callee, int argc, mcvalue_t* args);
TMPSTATIC MCINLINE bool mc_vmdo_tryoverloadoperator(mcstate_t* state, mcvalue_t left, mcvalue_t right, mcinternopcode_t op, bool* outoverloadfound);
TMPSTATIC mcvalue_t mc_vm_getlastpopped(mcstate_t* state);
TMPSTATIC bool mc_vm_haserrors(mcstate_t* state);
TMPSTATIC bool mc_vm_setglobalbyindex(mcstate_t* state, int ix, mcvalue_t val);
TMPSTATIC mcvalue_t mc_vm_getglobalbyindex(mcstate_t* state, int ix);
TMPSTATIC void mc_vm_setstackpos(mcstate_t* state, int nsp);
TMPSTATIC void mc_vm_stackpush(mcstate_t* vm, mcvalue_t obj);
TMPSTATIC mcvalue_t mc_vm_stackpop(mcstate_t* vm);
TMPSTATIC mcvalue_t mc_vm_stackget(mcstate_t* vm, int nthitem);
TMPSTATIC void mc_vm_thisstackpush(mcstate_t* vm, mcvalue_t obj);
TMPSTATIC mcvalue_t mc_vm_thisstackpop(mcstate_t* vm);
TMPSTATIC mcvalue_t mc_vm_thisstackget(mcstate_t* vm, int nthitem);
TMPSTATIC bool mc_vm_pushframe(mcstate_t* vm, mcvmframe_t frame);
TMPSTATIC bool mc_vm_popframe(mcstate_t* vm);
TMPSTATIC void mc_vm_rungc(mcstate_t* vm, mcbasicarray_t* constants);
TMPSTATIC MCINLINE bool mc_vmdo_callobject(mcstate_t* vm, mcvalue_t callee, int nargs);
TMPSTATIC mcvalue_t mc_vm_callnativefunction(mcstate_t* vm, mcvalue_t callee, mcastlocation_t srcpos, int argc, mcvalue_t* args);
TMPSTATIC bool mc_vm_checkassign(mcstate_t* state, mcvalue_t oldvalue, mcvalue_t nvalue);
TMPSTATIC MCINLINE bool mc_vmdo_opaddstring(mcstate_t* state, mcvalue_t valleft, mcvalue_t valright, mcvaltype_t righttype, mcopcode_t opcode);
TMPSTATIC MCINLINE bool mc_vmdo_math(mcstate_t* state, mcopcode_t opcode);
TMPSTATIC MCINLINE bool mc_vmdo_getindexpartial(mcstate_t* state, mcvalue_t left, mcvaltype_t lefttype, mcvalue_t index, mcvaltype_t indextype);
TMPSTATIC MCINLINE bool mc_vmdo_getindexfull(mcstate_t* state);
bool mc_vm_findclassfor(mcstate_t* state);
TMPSTATIC MCINLINE bool mc_vmdo_getdotindex(mcstate_t* state);
TMPSTATIC MCINLINE bool mc_vmdo_setindexpartial(mcstate_t* state, mcvalue_t left, mcvaltype_t lefttype, mcvalue_t index, mcvaltype_t indextype, mcvalue_t nvalue);
TMPSTATIC MCINLINE bool mc_vmdo_setindexfull(mcstate_t* state);
TMPSTATIC MCINLINE bool mc_vmdo_getvalueatfull(mcstate_t* state);
TMPSTATIC MCINLINE bool mc_vmdo_makefunction(mcstate_t* state, mcbasicarray_t* constants);
TMPSTATIC MCINLINE bool mc_vmdo_docmpvalue(mcstate_t* state, mcopcode_t opcode);
TMPSTATIC MCINLINE bool mc_vmdo_docmpvalgreater(mcstate_t* state, mcopcode_t opcode);
TMPSTATIC MCINLINE bool mc_vmdo_makearray(mcstate_t* state);
TMPSTATIC MCINLINE bool mc_vmdo_makemapstart(mcstate_t* state);
TMPSTATIC MCINLINE bool mc_vmdo_makemapend(mcstate_t* state);
TMPSTATIC bool mc_function_execfunction(mcstate_t* state, mcvalue_t function, mcbasicarray_t* constants);
void optprs_fprintmaybearg(FILE* out, const char* begin, const char* flagname, size_t flaglen, bool needval, bool maybeval, const char* delim);
void optprs_fprintusage(FILE* out, optlongflags_t* flags);
void mc_cli_printusage(char* argv[], optlongflags_t* flags, bool fail);
bool mc_cli_compileandrunsource(mcstate_t* state, mcvalue_t* vdest, const char* source);
bool mc_cli_compileandrunfile(mcstate_t* state, const char* filename);
void mc_cli_installargv(mcstate_t* state, int argc, char** argv, int beginat);
void mc_cli_installbuiltins(mcstate_t* state);
void mc_cli_installjsondummy(mcstate_t* state);
void mc_cli_installjsconsole(mcstate_t* state);
void mc_cli_installfauxjavascript(mcstate_t* state);
void mc_cli_installfileio(mcstate_t* state);
void mc_cli_installotherstuff(mcstate_t* state);
void mc_cli_printtypesize(const char* name, size_t sz);
void mc_cli_printtypesizes();
